### ISSUE TITLE
NoSuchMethodError: com.fasterxml.jackson.dataformat.yaml.YAMLFactory._decorate(Ljava/io/InputStream;Lcom/fasterxml/jackson/core/io/IOContext;)Ljava/io/InputStream

### ISSUE THREAD

**Issue by kchvilyov** [ukase/handlebars-petrovich4j#3]
I have got for code: Petrovich morpher = new Petrovich();
This error:
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.yaml.YAMLFactory._decorate(Ljava/io/InputStream;Lcom/fasterxml/jackson/core/io/IOContext;)Ljava/io/InputStream;
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:306) [jackson-dataformat-yaml-2.5.2.jar:2.5.2]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14) [jackson-dataformat-yaml-2.5.2.jar:2.5.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2080) [jackson-databind-2.2.3.jar:]
	at com.github.aleksandy.petrovich.rules.loader.YamlRulesLoader.load(YamlRulesLoader.java:30) [petrovich-1.2.1.jar:]
	at com.github.aleksandy.petrovich.rules.RulesProvider.<init>(RulesProvider.java:11) [petrovich-1.2.1.jar:]
	at com.github.aleksandy.petrovich.Petrovich.<init>(Petrovich.java:19) [petrovich-1.2.1.jar:]
	at com.github.aleksandy.petrovich.Petrovich.<init>(Petrovich.java:15) [petrovich-1.2.1.jar:]

<jackson.version>2.7.4</jackson.version>

**Comment by webkumo** [comment]
I can't understand why did you make a bug in this project...
According to your stack trace you tried to use different fork of library. In this project we are using library fork with main class
com.github.petrovich4j.Petrovich
But you used
com.github.aleksandy.petrovich.Petrovich
